Repository myriadsocial/myriad-federated, pull requests merged in 2022-10, with the labels that each got.

#60 integration wallet and social media statistics
  src/api/GET_TopCurrencies.ts
  src/api/GET_UsersGrowth.ts
  src/components/molecules/ChartBar/index.tsx
  src/components/molecules/ChartDoughnut/index.tsx
  src/components/molecules/ChartPie/index.tsx
  src/components/molecules/ChartTopCoint/index.tsx
  src/interface/DashboardInterface.ts
  src/interface/ServerListInterface.ts
  src/pages/dashboard/index.tsx
  src/utils/convertCamelCaseTitle/index.ts
Labels: feature

#63 ci: update node version
  .github/workflows/tester.yml
  .maintain/docker/Dockerfile
Labels: ci

#64 fix: update revision
  next.config.js
  src/api/GET_TopCurrencies.ts
  src/components/molecules/ChartBar/index.tsx
  src/components/molecules/ChartDoughnut/index.tsx
  src/components/molecules/ChartTopCoint/index.tsx
  src/interface/DashboardInterface.ts
  src/pages/_app.tsx
  src/pages/dashboard/index.tsx
  src/utils/dateFormatter/index.ts
Labels: fix

#65 feat: redirect help menu to email
  src/components/organisms/Siderbar/index.tsx
  src/utils/openUrl/index.ts
Labels: feature

#66 feat: Dynamic Metric on Dashboard
  next.config.js
  src/api/GET_serversMatric.ts
  src/components/organisms/Header/index.tsx
  src/hooks/use-auth.hook.ts
  src/pages/dashboard/index.tsx
Labels: feature

#67 feat: integration instance
  package.json
  src/api/PATCH_EditInstance.ts
  src/api/axiosInstance.ts
  src/components/molecules/CardEditInstance/index.tsx
  src/components/molecules/CardInstanceLeft/index.tsx
  src/components/molecules/CardInstanceRight/index.tsx
  src/components/organisms/Header/index.tsx
  src/components/organisms/Siderbar/index.tsx
  src/navigations/index.tsx
  src/pages/api/[...all].ts
  src/pages/dashboard/index.tsx
  src/pages/dashboard/instance/edit.tsx
  src/pages/dashboard/instance/index.tsx
  yarn.lock
Labels: feature

#70 fix: update edit instance
  src/components/molecules/CardEditInstance/index.tsx
  src/pages/dashboard/instance/edit.tsx
Labels: fix

#71 feat: remove image on src
  src/images/Icons/ArrowUp.svg
  src/images/Icons/DragIndicator.svg
  src/images/Icons/Illustration.svg
  src/images/Icons/InfoIcon.svg
  src/images/Icons/Sort.svg
  src/images/Icons/Upload.svg
  src/images/Icons/facebook.svg
  src/images/Icons/magnifierIcon.svg
  src/images/Icons/myriad-circle.svg
  src/images/Icons/myriad-full-black.svg
  src/images/Icons/myriad-grey.svg
  src/images/Icons/myriad-logo-full.svg
  src/images/Icons/myriad.svg
  src/images/Icons/notif-default.svg
  src/images/Icons/official-badge.svg
  src/images/Icons/reddit.svg
  src/images/Icons/twitter.svg
Labels: feature

#72 fix: handle failed authentication
  src/hooks/use-auth.hook.ts
Labels: improvement

#74 cd: improve ci/cd
  .github/workflows/deployer.yml
  .github/workflows/release.yml
Labels: improvement
