Repository myriadsocial/myriad-federated, pull requests merged in 2022-09, with the labels that each got.

#25 slicing dashboard
  package.json
  public/icons/CountExperiences.svg
  public/icons/CountPost.svg
  public/icons/CountTip.svg
  public/icons/CountUser.svg
  public/icons/Debio.svg
  public/icons/Kusama.svg
  public/icons/Myriad.svg
  public/icons/Near.svg
  public/icons/Polkadot.svg
  public/icons/index.ts
  src/components/molecules/CardTotal/index.tsx
  src/components/organisms/CardRecentReported/index.tsx
  src/components/organisms/DashCounter/index.tsx
  src/components/organisms/Siderbar/index.tsx
  src/layout/ContentLayout.tsx
  src/pages/dashboard/index.tsx
  src/pages/instance/index.tsx
  yarn.lock
Labels: feature

#28 fix: added new methode create instance
  src/components/molecules/CardTotal/index.tsx
  src/components/organisms/CardRecentReported/index.tsx
  src/components/organisms/DashCounter/index.tsx
  src/helpers/extension.ts
  src/lib/services/polkadot-js.ts
  src/pages/instance/index.tsx
Labels: improvement

#27 feat: ui slicing setting
  src/components/atoms/CardInstance/index.tsx
  src/pages/dashboard/instance/index.tsx
  src/pages/dashboard/settings/index.tsx
Labels: feature

#31 fix: removed unused field in ServerListProps interface
  src/components/Instance/Instance.styles.ts
  src/components/Instance/InstanceComponent.tsx
  src/components/Instance/InstanceList.tsx
  src/components/Instance/InstanceStepperModal.tsx
  src/components/ServerList/ServerList.tsx
  src/interface/ServerListInterface.ts
  src/lib/services/polkadot-js.ts
  src/pages/_document.tsx
Labels: improvement

#33 fix: blockchain context
  src/components/Instance/InstanceComponent.tsx
  src/components/Instance/InstanceList.tsx
  src/components/ServerList/ServerList.tsx
  src/components/common/Blockchain/Blockchain.provider.tsx
  src/components/common/Blockchain/useIsMountedRef.hook.ts
  src/hooks/use-all-instances.hooks.ts
  src/hooks/use-instances.hooks.ts
  src/hooks/use-owner-instances.hooks.ts
  src/interface/ServerListInterface.ts
  src/lib/services/polkadot-js.ts
  src/pages/_app.tsx
Labels: improvement

#34 fix typo
  src/components/atoms/Button/index.tsx
  src/components/atoms/CardInstance/index.tsx
  src/components/organisms/DashCounter/index.tsx
  src/pages/dashboard/index.tsx
Labels: fix

#35 fix: typo
  src/components/atoms/CardInstance/index.tsx
  src/pages/dashboard/index.tsx
Labels: fix

#36 fix: url reported comment
  src/components/Instance/InstanceStepperModal.tsx
  src/components/ServerList/ServerList.tsx
  src/components/ServerList/Shimer.tsx
  src/components/atoms/CardInstance/index.tsx
  src/components/atoms/DropdownFilter/index.tsx
  src/components/atoms/ListReporter/index.tsx
  src/components/molecules/CardEditInstance/index.tsx
  src/components/organisms/Header/index.tsx
  src/components/organisms/Table/index.tsx
  src/interface/UserInterface.ts
  src/pages/dashboard/index.tsx
  src/pages/dashboard/notification/index.tsx
  src/pages/dashboard/post/index.tsx
  src/pages/dashboard/post/responded.tsx
  src/pages/dashboard/settings/index.tsx
  src/pages/dashboard/user/index.tsx
  src/pages/dashboard/user/responded.tsx
  tailwind.config.js
Labels: fix

#37 fix: format number
  src/utils/numberFormatter/index.ts
Labels: fix

#38 fix: typo on experiences
  src/components/ServerList/ServerList.tsx
  src/components/atoms/CardInstance/index.tsx
Labels: fix

#39 feat: add toaster if create instance failed
  package.json
  src/components/Instance/InstanceComponent.tsx
  src/components/molecules/Snackbar/Snackbar.interface.ts
  src/components/molecules/Snackbar/Snackbar.style.ts
  src/components/molecules/Snackbar/Snackbar.tsx
  src/components/molecules/Snackbar/useEnqueueSnackbar.hook.tsx
  src/hooks/use-instances.hooks.ts
  src/pages/_app.tsx
  yarn.lock
Labels: feature

#40 fix: adjusted styling on text
  src/components/Instance/InstanceStepperModal.tsx
Labels: fix

#42 fix: changed text
  src/components/Instance/InstanceStepperModal.tsx
Labels: fix

#43 feat: error handling auth dashboard
  src/components/Instance/InstanceList.tsx
Labels: feature

#44 fix: error handler when user not exists
  src/components/Instance/InstanceComponent.tsx
  src/components/Instance/InstanceList.tsx
  src/components/ServerList/ServerList.tsx
  src/hooks/use-instances.hook.ts
  src/hooks/use-polkadot-app.hook.ts
Labels: improvement

#45 fix: improve dashboard security
  .env-template
  next.config.js
  package.json
  src/api/POST_Admin.ts
  src/components/Instance/InstanceComponent.tsx
  src/components/Instance/InstanceList.tsx
  src/components/ServerList/ServerList.tsx
  src/components/organisms/Header/index.tsx
  src/helpers/parseCookie.ts
  src/hooks/use-auth.hook.ts
  src/lib/crypto.ts
  src/pages/_app.tsx
  src/pages/api/[...all].ts
  src/pages/api/auth/login.ts
  src/pages/dashboard/help/index.tsx
  src/pages/dashboard/index.tsx
  src/pages/dashboard/instance/edit.tsx
  src/pages/dashboard/instance/index.tsx
  src/pages/dashboard/notification/index.tsx
  src/pages/dashboard/post/index.tsx
  src/pages/dashboard/post/responded.tsx
  src/pages/dashboard/settings/index.tsx
  src/pages/dashboard/user/index.tsx
  src/pages/dashboard/user/responded.tsx
  src/pages/index.tsx
  src/pages/instance/index.tsx
  yarn.lock
Labels: improvement

#47 fix: change env name
  .env-template
  next.config.js
Labels: improvement

#48 ci: move registry to docker hub
  .dockerignore
  .github/workflows/analyzer.yml
  .github/workflows/builder.yml
  .github/workflows/create-tags.yml
  .github/workflows/deployer.yml
  .github/workflows/mlc_config.json
  .github/workflows/rcb_config.json
  .github/workflows/release.yml
  .github/workflows/tester.yml
  .maintain/docker/Dockerfile
  next.config.js
  package.json
Labels: ci

#49 ci: fix deployment
  .github/workflows/deployer.yml
  .github/workflows/release.yml
Labels: ci

#46 create component switch account
  package.json
  public/icons/IcAccountPolkadot.svg
  public/icons/IcCopyOutline.svg
  public/icons/index.ts
  src/components/Instance/InstanceComponent.tsx
  src/components/Instance/InstanceHeader.tsx
  src/components/PolkadotAccountList/PolkadotAccountList.tsx
  src/components/ServerList/ServerList.tsx
  src/components/atoms/Button/index.tsx
  src/components/atoms/ListSwithAccount/index.tsx
  src/components/molecules/SwitchAccount/index.tsx
  src/pages/instance/index.tsx
  yarn.lock
Labels: feature

#50 feat: added proxy middleware
  package.json
  src/middleware.tsx
  src/pages/dashboard/help/index.tsx
  src/pages/dashboard/index.tsx
  src/pages/dashboard/instance/edit.tsx
  src/pages/dashboard/instance/index.tsx
  src/pages/dashboard/notification/index.tsx
  src/pages/dashboard/post/index.tsx
  src/pages/dashboard/post/responded.tsx
  src/pages/dashboard/settings/index.tsx
  src/pages/dashboard/user/index.tsx
  src/pages/instance/index.tsx
  yarn.lock
Labels: improvement

#51 fix: update label & fix typo
  public/icons/index.ts
  src/components/Instance/InstanceStepperModal.tsx
Labels: fix

#52 fet: add back button from instace to landing page
  public/icons/IcBackPrimary.svg
  public/icons/index.ts
  src/components/Instance/InstanceComponent.tsx
  src/components/Instance/InstanceHeader.tsx
Labels: feature

#53 feat: add switch instance and refactoring component
  src/components/atoms/ListSwithAccount/index.tsx
  src/components/atoms/Modal/Modal.tsx
  src/components/molecules/PolkadotAccountList/PolkadotAccountList.styles.ts
  src/components/molecules/PolkadotAccountList/PolkadotAccountList.tsx
  src/components/molecules/PolkadotAccountList/index.ts
  src/components/molecules/Search/SearchBox.interfaces.ts
  src/components/molecules/Search/SearchBox.tsx
  src/components/molecules/Search/SearchBoxContainer.tsx
  src/components/molecules/Search/index.ts
  src/components/molecules/Search/search-box.styles.ts
  src/components/molecules/SwitchAccount/index.tsx
  src/components/molecules/common/Blockchain/Blockchain.context.ts
  src/components/molecules/common/Blockchain/Blockchain.provider.tsx
  src/components/molecules/common/Blockchain/useBlockchain.hook.ts
  src/components/molecules/common/Blockchain/useIsMountedRef.hook.ts
  src/components/molecules/common/PolkadotLink.component.tsx
  src/components/molecules/common/show-if.component.tsx
  src/components/organisms/Header/index.tsx
  src/components/organisms/Instance/Instance.styles.ts
  src/components/organisms/Instance/InstanceComponent.tsx
  src/components/organisms/Instance/InstanceHeader.tsx
  src/components/organisms/Instance/InstanceList.tsx
  src/components/organisms/Instance/InstanceStepperModal.tsx
  src/components/organisms/ServerList/ServerList.tsx
  src/components/organisms/ServerList/Shimer.tsx
  src/components/organisms/ServerList/server-list.styles.ts
  src/hooks/use-auth.hook.ts
  src/hooks/use-instances.hook.ts
  src/pages/_app.tsx
  src/pages/index.tsx
  src/pages/instance/index.tsx
Labels: feature

#54 feat: improve switch instance
  src/components/atoms/ListSwithAccount/index.tsx
  src/components/organisms/Header/index.tsx
  src/components/organisms/Instance/InstanceList.tsx
  src/components/organisms/ServerList/ServerList.tsx
  src/hooks/use-auth.hook.ts
Labels: improvement

#55 fix: bug switch instance on testnet
  src/components/organisms/Header/index.tsx
  src/hooks/use-auth.hook.ts
  src/hooks/use-instances.hook.ts
Labels: fix

#56 feat : Add new metrics for dashboard
  public/icons/CountComments.svg
  public/icons/CountSubcriptions.svg
  public/icons/CountTips.svg
  public/icons/index.ts
  src/components/atoms/ListMedian/index.tsx
  src/components/molecules/CardInstance/index.tsx
  src/components/molecules/CardTotal/index.tsx
  src/components/molecules/ChartBar/index.tsx
  src/components/molecules/ChartDoughnut/index.tsx
  src/components/molecules/ChartPie/index.tsx
  src/components/molecules/ChartTopCoint/index.tsx
  src/components/molecules/MedianStatistics/index.tsx
  src/components/molecules/Snackbar/Snackbar.style.ts
  src/components/molecules/Snackbar/Snackbar.tsx
  src/components/organisms/CardRecentReported/index.tsx
  src/components/organisms/DashCounter/index.tsx
  src/components/organisms/Header/index.tsx
  src/components/organisms/Instance/InstanceList.tsx
  src/components/organisms/ServerList/ServerList.tsx
  src/constans/array.ts
  src/interface/UserInterface.ts
  src/layout/ContentLayout.tsx
  src/pages/_app.tsx
  src/pages/dashboard/index.tsx
  src/pages/dashboard/post/index.tsx
  src/pages/dashboard/post/responded.tsx
  src/pages/dashboard/user/index.tsx
  src/pages/dashboard/user/responded.tsx
  src/utils/calWidthScreen/index.ts
Labels: feature

#57 feat: integration matric dashboard
  src/components/atoms/ListMedian/index.tsx
  src/components/molecules/ChartDoughnut/index.tsx
  src/components/molecules/ChartPie/index.tsx
  src/components/molecules/MedianStatistics/index.tsx
  src/hooks/use-instances.hook.ts
  src/interface/ServerListInterface.ts
  src/pages/dashboard/index.tsx
Labels: feature

#58 fix: color icon snackbar
  src/components/molecules/Snackbar/Snackbar.tsx
  src/components/organisms/ServerList/ServerList.tsx
Labels: fix

#59 fix: total post instances
  src/hooks/use-instances.hook.ts
Labels: improvement
