Repository myriadsocial/myriad-federated, pull requests merged in 2022-08, with the labels that each got.

#16 ci: added new env
  .github/workflows/deployer.yml
Labels: ci

#18 ci: fixed permission
  .github/workflows/deployer.yml
Labels: ci

#19 ci: fix deployment
  .github/workflows/deployer.yml
Labels: ci

#20 update env & fix bug
  next.config.js
  package.json
  src/components/ServerList/ServerList.tsx
  src/layout/ContentLayout.tsx
  src/pages/index.tsx
  src/pages/instance/index.tsx
  yarn.lock
Labels: improvement

#21 fix styling
  src/components/Empty/Empty.styles.ts
  src/components/Empty/Empty.tsx
  src/components/Empty/index.ts
  src/components/Icons/Core.tsx
  src/components/Icons/index.ts
  src/components/Search/SearchBox.tsx
  src/components/ServerList/ServerList.tsx
  src/components/ServerList/server-list.styles.ts
  src/components/atoms/AvatarWithName/index.tsx
  src/components/atoms/Button/index.tsx
  src/components/atoms/CardInstance/index.tsx
  src/components/atoms/DropdownFilter/index.tsx
  src/components/atoms/EmptyState/index.tsx
  src/components/atoms/ListAllNotifications/index.tsx
  src/components/atoms/ListReporter/index.tsx
  src/components/atoms/ListSidebar/index.tsx
  src/components/atoms/SubListSidebar/index.tsx
  src/components/molecules/CardInstanceLeft/index.tsx
  src/components/molecules/Modal/index.tsx
  src/pages/dashboard/index.tsx
  src/pages/dashboard/post/index.tsx
  src/pages/dashboard/post/responded.tsx
  src/pages/dashboard/user/index.tsx
  src/pages/dashboard/user/responded.tsx
  src/pages/instance/index.tsx
  styles/globals.css
  tailwind.config.js
Labels: improvement

#23 fix: url report user
  next.config.js
  src/components/ServerList/ServerList.tsx
  src/components/atoms/CardInstance/index.tsx
  src/lib/services/polkadot-js.ts
  src/pages/dashboard/user/index.tsx
  src/pages/dashboard/user/responded.tsx
  src/utils/numberFormatter/index.ts
Labels: fix

#24 fix: styling
  src/constans/array.ts
  src/navigations/index.tsx
  src/pages/dashboard/post/index.tsx
  src/pages/dashboard/post/responded.tsx
  src/pages/dashboard/user/responded.tsx
  src/pages/instance/index.tsx
Labels: fix

#22 feat: connect wallet
  .eslintignore
  .eslintrc.js
  .eslintrc.json
  .prettierignore
  .prettierrc.json
  next.config.js
  package.json
  postcss.config.js
  public/icons/index.ts
  src/components/PolkadotAccountList/PolkadotAccountList.styles.ts
  src/components/PolkadotAccountList/PolkadotAccountList.tsx
  src/components/PolkadotAccountList/index.ts
  src/components/Search/SearchBox.tsx
  src/components/ServerList/ServerList.tsx
  src/components/ServerList/server-list.styles.ts
  src/components/atoms/AvatarWithName/index.tsx
  src/components/atoms/Button/index.tsx
  src/components/atoms/CardInstance/index.tsx
  src/components/atoms/DropdownFilter/index.tsx
  src/components/atoms/EmptyState/index.tsx
  src/components/atoms/ListAllNotifications/index.tsx
  src/components/atoms/ListReporter/index.tsx
  src/components/atoms/ListSidebar/index.tsx
  src/components/atoms/Modal/Modal.styles.ts
  src/components/atoms/Modal/Modal.tsx
  src/components/atoms/Modal/Modal.types.ts
  src/components/atoms/Modal/index.ts
  src/components/atoms/SubListSidebar/index.tsx
  src/components/common/PolkadotLink.component.tsx
  src/components/common/show-if.component.tsx
  src/components/molecules/CardInstanceLeft/index.tsx
  src/components/molecules/Modal/index.tsx
  src/components/organisms/Header/index.tsx
  src/components/organisms/Siderbar/index.tsx
  src/constans/array.ts
  src/hooks/server-list.hooks.ts
  src/hooks/use-polkadot-app.hooks.ts
  src/layout/ContentLayout.tsx
  src/lib/services/polkadot-js.ts
  src/navigations/index.tsx
  src/pages/_app.tsx
  src/pages/api/[...all].ts
  src/pages/api/hello.ts
  src/pages/dashboard/index.tsx
  src/pages/dashboard/post/index.tsx
  src/pages/dashboard/post/responded.tsx
  src/pages/dashboard/user/index.tsx
  src/pages/dashboard/user/responded.tsx
  src/pages/index.tsx
  src/pages/instance/index.tsx
  src/utils/numberFormatter/index.ts
  styles/globals.css
  tailwind.config.js
  yarn.lock
Labels: feature

#26 fix: improved connect wallet
  package.json
  src/components/ServerList/ServerList.tsx
  src/components/atoms/Button/index.tsx
  src/hooks/server-list.hooks.ts
  src/interface/ServerListInterface.ts
  src/lib/services/polkadot-js.ts
  src/pages/index.tsx
  src/pages/instance/index.tsx
  yarn.lock
Labels: improvement
