Repository myriadsocial/myriad-federated, pull requests merged in 2023-02, with the labels that each got.

#90 feat: implement withdraw reward feature
  src/api/GET_Currencies.ts
  src/api/GET_Network.ts
  src/components/molecules/CardInstance/index.tsx
  src/components/molecules/Staked/UnclaimReward.tsx
  src/components/organisms/Instance/InstanceComponent.tsx
  src/components/organisms/Instance/InstanceList.tsx
  src/components/organisms/Instance/InstanceStepperModal.tsx
  src/components/organisms/ServerList/ServerList.tsx
  src/hooks/use-instances.hook.ts
  src/interface/CurrencyInterface.ts
  src/interface/NetworkInterface.ts
  src/interface/RewardBalanceInterface.ts
  src/interface/ServerListInterface.ts
  src/lib/services/polkadot-js.ts
Labels: improvement

#91 fix: updated amount data type
  src/components/molecules/Staked/UnclaimReward.tsx
  src/hooks/use-instances.hook.ts
  src/interface/CurrencyInterface.ts
  src/interface/RewardBalanceInterface.ts
  src/lib/services/polkadot-js.ts
Labels: improvement

#94 fix: implement gas fee on stake, claim reward, and deregister card
  src/api/GET_Currencies.ts
  src/components/molecules/CardInstance/index.tsx
  src/components/molecules/Staked/Deregister.tsx
  src/components/molecules/Staked/TotalStaked.tsx
  src/components/molecules/Staked/UnclaimReward.tsx
  src/components/organisms/Instance/InstanceList.tsx
  src/hooks/use-instances.hook.ts
  src/lib/services/polkadot-js.ts
Labels: improvement

#95 fix: update account balance when claim reward
  src/hooks/use-instances.hook.ts
Labels: improvement

#96 fix: hide buy myria when unstaked modal showing
  src/components/molecules/Staked/TotalStaked.tsx
Labels: improvement

#97 feat: implement create instance with stake amount
  src/components/atoms/ListWallet/index.tsx
  src/components/molecules/CardInstance/index.tsx
  src/components/molecules/Staked/TotalStaked.tsx
  src/components/molecules/Staked/UnclaimReward.tsx
  src/components/molecules/SwitchNetwork/index.tsx
  src/components/organisms/Header/index.tsx
  src/components/organisms/Instance/InstanceComponent.tsx
  src/components/organisms/Instance/InstanceList.tsx
  src/components/organisms/Instance/InstanceStepperModal.tsx
  src/components/organisms/ServerList/ServerList.tsx
  src/helpers/formatNumber.tsx
  src/hooks/use-instances.hook.ts
  src/interface/CurrencyInterface.ts
  src/lib/services/polkadot-js.ts
Labels: feature

#99 fix: handle create instance
  src/components/organisms/Instance/InstanceStepperModal.tsx
Labels: improvement

#108 fix: login dashboard
  src/pages/api/auth/login.ts
  src/pages/api/hello.ts
Labels: improvement

#106 chore(main): release 1.0.0
  CHANGELOG.md
  package.json
Labels: autorelease: pending
